Define an API surface between Spezi Data Pipeline and Python notebook
StanfordSpezi/SpeziDataPipelineTemplate pull request #10
Opened 2024-03-22 02:01 UTC by Vicbi

# *Define an API surface between Spezi Data Pipeline and Python notebook*

## :recycle: Current situation & Problem
This PR addresses issue [#7](https://github.com/StanfordSpezi/spezi-data-pipeline/issues/7). The current helper.py file lacks structure and does not offer a clear API surface.

## :gear: Release Notes 
- Introduced the basis for a structured API surface for the Spezi Data Pipeline to facilitate easier integration with Python notebooks.
- Utilized the [fhir.resources](https://pypi.org/project/fhir.resources/) package for describing FHIR resources.
- Implemented [Firebase QUERY](https://firebase.google.com/docs/firestore/query-data/queries#python) for querying specific LOINC codes directly from Firebase, in order to avoid unnecessary data download and ptimize data retrieval.
- Added a process_FHIR_data() function for basic filtering and analysis of acquired data, streamlining data processing tasks for users' convenience.

## :books: Documentation
### API Surface Structure
```kotlin
spezi_data_pipeline/
│
├── spezi_data_pipeline/
│   ├── __init__.py                          
│   ├── data_access/
│   │   ├── __init__.py
│   │   ├── firebase_FHIR_data_access.py
│   │       ├── class EnhancedObservation
│   │       |   ├── __init__(self, observation: Observation, UserId=None)
│   │       ├── class FirebaseFHIRAccess
│   │           ├── __init__(self, service_account_key_file: str, project_id: str) -> None
│   │           ├── connect(self) -> None
│   │           └── fetch_data(
        self, 
        collection_name: str = 'users', 
        subcollection_name: str = 'HealthKit', 
        loinc_codes: Optional[List[str]] = None
    ) -> List[EnhancedObservation]
│   │
│   ├── data_flattening/                  
│   │   ├── __init__.py
│   │   └── FHIR_data_flattener.py          
│   │       ├── class FHIRDataFrame
│   │       |   ├── __init__(self, data: pd.DataFrame, resource_type: str = "Observation") -> None
│   │       |   ├── df(self) -> pd.DataFrame
│   │       └── flatten_FHIR_resources(FHIR_resources: List[EnhancedObservation]) -> FHIRDataFrame
│   │
│   ├── data_analysis/
│   │   ├── __init__.py
│   │   ├── data_analyzer.py                    
│   │   |   └── class FHIRDataProcessor
│   │   |       ├── __init__(self)
│   │   |       ├── process_FHIR_data(self, flattened_FHIRDataFrame: FHIRDataFrame) -> FHIRDataFrame
│   │   |       ├── calculate_daily_data(self, group_FHIRDataFrame: FHIRDataFrame) -> FHIRDataFrame
│   │   |       ├── calculate_average_data(self, group_FHIRDataFrame: FHIRDataFrame) -> FHIRDataFrame
|   |   |       ├── def _finalize_group(self, original_df: pd.DataFrame, aggregated_df: pd.DataFrame, prefix: str) -> pd.DataFrame
|   |   |       ├── filter_outliers(self, flattened_FHIRDataFrame: FHIRDataFrame, value_range=None) -> FHIRDataFrame
|   |   |       ├── validate_columns(self, flattened_FHIRDataFrame: FHIRDataFrame) -> None
|   |   |       ├── select_data_by_user(self, flattened_FHIRDataFrame: FHIRDataFrame, user_id: str) -> FHIRDataFrame
|   |   |       ├── select_data_by_dates(self, flattened_FHIRDataFrame: FHIRDataFrame, start_date: str, end_date: str) -> FHIRDataFrame
│   │   |       └── calculate_moving_average(self, flattened_FHIRDataFrame: FHIRDataFrame, n=7) -> FHIRDataFrame
│   │
│   ├── data_visualization/
│   │   ├── __init__.py
│   │   ├── data_visualizer.py              
│   │   │   └── class DataVisualizer(FHIRDataProcessor)
│   │   |       ├── __init__(self)
│   │   |       ├── set_date_range(self, start_date: str, end_date: str)
│   │   |       ├── set_user_ids(self, user_ids: List[str])
│   │   |       ├── set_y_bounds(self, y_lower: float, y_upper: float)
│   │   |       ├── set_same_plot(self, same_plot: bool)
│   │   |       ├── set_dpi(self, dpi: float)
│   │   │       └── create_static_plot(self, flattened_FHIRDataFrame: FHIRDataFrame) -> Optional[plt.Figure]
│   │
│   ├── data_export/
│   │   ├── __init__.py
│   │   ├── data_exporter.py
│   │   │   └── class DataExporter(DataVisualizer)
│   │   |       ├── __init__(self, flattened_FHIRDataFrame: FHIRDataFrame)
│   │   |       ├── export_to_csv(self, filename)
│   │   │       └── create_and_save_plot(self, filename)
│   │
│   └── utils/
│       ├── __init__.py
│       └── helpers.py
│           └── snake_case(s: str) -> str
|
├── tests/ (currently missing)
│   ├── __init__.py
│   ├── test_data_access/
│   ├── ...
│   └── test_export/
│
├── docs/ (currently missing)
│   ├── index.md
│   ├── setup.md
│   └── usage.md
│
├── examples/ (currently missing)
│   └── example_usage.py                                     
│
├── setup.py (currently missing)
├── README.md
├── LICENSE
└── .gitignore

```

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2024-03-23 00:51 UTC, PSchmiedmayer requested changes
@Vicbi Thank you for the PR and first version of the decomposed architecture; it is great to see some next steps and to see the architecture and elements that we discussed taking shape within the PR!

I started to dive into the code but came up with a lot of basic code style feedbacks so I decided to fist install a linter in a GitHub action and I added a proposed linting file to define a common code style to agree on.

I think this would be a great next step. Let me know what you think about this configuration. Feel free to adapt it and incorporate the elements that it provides as feedback into this PR so we have a well-formatted codebase to start with. 

In addition to that, I have also provided some high-level feedback on some functions and elements; I can provide some more aspects once we have an agreement about the code style guidelines 🚀

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_access/firebase_FHIR_data_access.py
> +        self.UserId = UserId
I don't think that we need to provide a wrapper type around Observation. Observation has a subject ID and we could use that to encode the user ID: https://build.fhir.org/observation-definitions.html#Observation.subject.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_access/firebase_FHIR_data_access.py
> +        }
I am not sure what the reason is for matching for the complete coding information. Matching agains the main code should be sufficient. We can't really guarantee that the human readable description will always be the same. the coding system & code should be unique and identifiable.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_analysis/data_analyzer.py
> +        }
I think it might make sense to abstract this in a separate type that provides a mapping scheme and also some common functionalities that are associated with a coding scheme.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_analysis/data_analyzer.py
> +        })
We should consider that some of these types might have valuable information attached beyond the initial field. Might not be relevant now but could be important in the future.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_analysis/data_analyzer.py
> +        # final_df['Display'] = final_df['Display'].apply(lambda x: f"Updated display info based on {prefix}")
Would be good to remove commented out code here and in other files 👍

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_analysis/data_analyzer.py
> +    def validate_columns(self, flattened_FHIRDataFrame: FHIRDataFrame) -> None:
This could move into a function of the `FHIRDataFrame` 👍

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_analysis/data_analyzer.py
> +    def calculate_moving_average(self, flattened_FHIRDataFrame: FHIRDataFrame, n=7) -> FHIRDataFrame:
Would be great to group related functions next to each other for a better readability 👍

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_export/data_exporter.py
> +        self.end_date = '2022-12-31'
Would be good to remove hard-coded values like this.

Similar to the other visualization function we should share a similar type (maybe a configuration type) across the modules.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_flattening/FHIR_data_flattener.py
> +    for FHIR_obj in FHIR_resources:
We should only loop through observations if the type has been passed in as Observation.

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_flattening/FHIR_data_flattener.py
> +    def __init__(self, data: pd.DataFrame, resource_type: str = "Observation") -> None:
Is there a possibility that the FHIR package does provide an enum like value for resource types that we could use here instead of a string?

2024-03-23 00:51 UTC, PSchmiedmayer commented on data_visualization/data_visualizer.py
> +    def set_same_plot(self, same_plot: bool):
As noted in the notebook, the name might not be as expressive as it could be.

2024-04-11 05:15 UTC, Vicbi commented
Hi @PSchmiedmayer, I've pushed the code updates to the defineAPISurface branch. I chose to keep the ECGObservation class (potentially, it can be a wrapper for the Observation class). This approach simplifies method selection across modules based on data type, eliminating the need for conditions to exclude ECG LOINC code from the FHIRDataFrame object. Moving forward, we might consider renaming ECGObservation to cover all LOINC codes with attributes similar to ECG data.

Thank you for reviewing the changes. Please note that the README hasn't been updated to include these adjustments yet, but it will be shortly. However, the docstrings within the modules are up-to-date. 

Feel free to reach out if you need any help!

2024-04-18 18:01 UTC, PSchmiedmayer requested changes
Thank you for all the work here @Vicbi; happy to see this merged soon! 🚀

I took a look at the code and would have a few high-level suggestions
- The **ECG parsing** is currently assuming a very rigid structure of the elements ordered in the correct way. We can't really guarantee the order in the JSON files and should therefore rather use the coding schemes attached to the elements to parse this.
- **Unit Testing CI Setup:** We currently only execute the notebook for the CI setup but not any of the unit test as far as I can see. It would be good if they are executed as part of the GitHub Action CI setup.
- Related to that: **Test Coverage**. Thank you for writing some first tests. I think it would be important to automatically asses what lines are already covered and where we are missing tests to ensure that the code is working as expected. We currently use CodeCov (https://about.codecov.io) for all our projects and I would suggest to use it here as well to generate automated coverage reports. They have some good documentation for python code.
- **Code Linting**: The current lint rules still throw some errors that would be great to be addressed before we merge the PR.
- As discussed, we will also need to adjust the **README** to reflect the latest changes.

Apart from this: I would suggest to merge the PR without too many smaller changes to ensure that we have a reworked state in the main branch and we can use subsequent smaller PRs and our meetings to discuss smaller changes to refine the API.

2024-04-18 20:19 UTC, Vicbi commented on tests/test_data_access.py
> +"""
Will do in the next iteration! I intend to add more tests too :+1:

2024-04-18 23:26 UTC, Vicbi commented on data_flattening/fhir_resources_flattener.py
> +ECG_SAMPLEDDATA_PART3_LOCATION = 7
The `extract_component_info(observation: Any) -> dict:` function was updated to loop through all the components of the observation.component code path. The visualisation module was updated accordingly to handle the new data structure in the flattened FHIRDataFrame.

2024-04-19 00:58 UTC, PSchmiedmayer commented on data_flattening/fhir_resources_flattener.py
> +ECG_SAMPLEDDATA_PART3_LOCATION = 7
Thank you @Vicbi 🚀

2024-04-22 23:11 UTC, PSchmiedmayer approved these changes
Great job! 🎉

2024-04-22 23:17 UTC, merged