Prepare Spezi Data Pipeline for PyPI Distribution
StanfordSpezi/SpeziDataPipelineTemplate pull request #14
Opened 2024-04-30 06:34 UTC by Vicbi

# *Prepare Spezi Data Pipeline for PyPI Distribution*

## :recycle: Current situation & Problem
This PR addresses the necessary configuration and organization for distributing the Spezi Data Pipeline tool through PyPI [Issue #13](https://github.com/StanfordSpezi/SpeziDataPipelineTemplate/issues/13).

## :gear: Release Notes 

- Develops comprehensive tests to ensure functionality.
- Implements Hatch as the package manager to handle project environments and dependencies.
- Reorganizes the project to adopt the standard Python package structure.

## :books: Documentation
Documentation is updated.

## :white_check_mark: Testing
The testing suite has been expanded to cover most functionalities according to the coverage criteria set by CodeCov. 

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2024-05-16 18:55 UTC, PSchmiedmayer requested changes
Thank you for all the improvement @Vicbi! 

I looked at the different changes and improvements and added comments throughout the code. Mostly around the automation setup and elements around this.

Thank you for adding so many tests in this PR; provides tremendous value!

2024-05-18 20:24 UTC, Vicbi commented on pyproject.toml
> +    { name = "Vasiliki Bikia", email = "bikia@stanford.edu" }
Absolutely yes! Would be great to automate the contributors generation, I'll update it!

2024-05-18 20:26 UTC, Vicbi commented on pyproject.toml
> +description = "A comprehensive data pipeline for processing and analyzing FHIR data using Firebase and FHIR standards."
I like the suggestion regarding the Firebase specification! 👍

2024-05-22 01:37 UTC, Vicbi commented on .github/workflows/publish-to-pypi.yml
> +      - '*'
I have added a script that automatically updates the Hatch project version based on the latest Git tag. It contains functions to retrieve the latest Git tag and update the Hatch version in the `pyproject.toml` configuration file. The script is intended to be run as a standalone program.

2024-05-22 01:46 UTC, Vicbi commented on .github/workflows/publish-to-pypi.yml
> +        hatch publish
I have created an issue so that we can work more thoroughly on this in a separate PR. Feel free to add comments/ideas there! 👍

2024-05-22 01:48 UTC, Vicbi commented on pyproject.toml
> +    { name = "Vasiliki Bikia", email = "bikia@stanford.edu" }
I added a script that should automatically update the authors in the `pyproject.toml` using as input the CONTRIBUTORS.md file in the root of the directory.

2024-05-23 05:25 UTC, PSchmiedmayer approved these changes
Thank you for all the improvements @Vicbi! I only had a few comments on restructuring the GitHub Actions and when the different scripts should be called.

Feel free to merge the PR once these elements are addressed, thank you for all the work that went into the PR, the improvements in test coverage are really nice 🚀

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/build-and-test.yml
> +          python-version: "3.10.9"
I would suggest to consistently use the setup python function, e.g., above we don't pass in a python version while we pass in a python version here.

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/build-and-test.yml
> +          path: SpeziDataPipelineTemplate.pdf
I think it might make sense to separate the notebook check from the run of the unit tests to make it eventually easier to separate this out + ensure that e.g., the notebook is still tested even if the unit tests fail and its easier to identify this in the merge checks.

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/publish-to-pypi.yml
> +        uses: actions/checkout@v2
We should use the latest checkout version as in the other GitHub Actions.

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/publish-to-pypi.yml
> +      - '*'
Very nice, thank you for creating the script.

It would make sense to call this script within this GitHub Action to ensure that the version is correctly set when we make a release. Otherwise we would first need to run the script and then create a release and move the tag accordingly. The goal of the script would be to automate this setup here so we don't have to commit version updates before we tag a release.

2024-05-23 05:25 UTC, PSchmiedmayer commented on CONTRIBUTORS.md
Thank you for creating this file 🎉

2024-05-23 05:25 UTC, PSchmiedmayer commented on pyproject.toml
> +
Great to see that this is automated. It would make sense to remove the authors here and add a comment that this is automatically generated (similar to the one at the placeholder as for the version number (0.0.0)).

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/publish-to-pypi.yml
> +
I would also suggest to run the update authors script here before building and publishing the package.

2024-05-23 05:25 UTC, PSchmiedmayer commented on .github/workflows/update-authors.yml
I would suggest to run both the update version and the update authors scripts right in the publish GitHub Action. I don't think we need to commit the results back into the repo (authors are listed in the md file anyways and the tag is part of the GitHub repo). The hatch toml file can continue to contain the placeholder values and will automatically be updated within the GitHub Action and then that data will be extracted to publish the package.

2024-05-23 05:25 UTC, PSchmiedmayer commented on README.md
Thank you for updating the README! 🚀

2024-05-23 05:25 UTC, PSchmiedmayer commented on pyproject.toml
> +version = "0.0.0"  # The version is automatically updated by the update_version.py script
Nice, tested the update locally and it worked well 👍

2024-05-23 05:25 UTC, PSchmiedmayer commented on update_authors.py
Thank you for the scripts, they look nice! I tested both locally and they worked well 🚀

2024-05-23 19:36 UTC, Vicbi commented on pyproject.toml
> +version = "0.0.0"  # The version is automatically updated by the update_version.py script
Planning to add some tests too!

2024-05-23 20:30 UTC, Vicbi commented on .github/workflows/update-authors.yml
I've updated the publish-to-pypi GitHub Action to run the scripts.

2024-05-23 20:36 UTC, merged